<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T01_csiswa_model extends CI_Model
{

    public $table = 't01_csiswa';
    public $id = 'idcsiswa';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idcsiswa', $q);
		$this->db->or_like('Nama', $q);
		$this->db->or_like('Alamat', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idcsiswa', $q);
		$this->db->or_like('Nama', $q);
		$this->db->or_like('Alamat', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // get all not registered
    function get_all_not_registered()
    {
        // $this->db->order_by($this->id, $this->order);
        // $this->db->where_not_in($this->id, 'select idcsiswa from t30_csiswa_sekolah');
        // return $this->db->get($this->table)->result();
        $q = "select * from " . $this->table . " where idcsiswa not in (select idcsiswa from t30_csiswa_sekolah)
            order by idcsiswa asc";
        return $this->db->query($q)->result();
    }

}

/* End of file T01_csiswa_model.php */
/* Location: ./application/models/T01_csiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-16 03:36:09 */
/* http://harviacode.com */
