<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T30_csiswa_sekolah_model extends CI_Model
{

    public $table = 't30_csiswa_sekolah';
    public $id = 'idcsiswasekolah';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('csiswa.Nama', $q);
        $this->db->or_like('csiswa.Alamat', $q);
		$this->db->or_like('sekolah.Nama', $q);
        $this->db->or_like('sekolah.Alamat', $q);
        $this->db
            ->select($this->table . '.*')
            ->select("concat(csiswa.Nama, ', ', csiswa.Alamat) as csiswaNamaAlamat")
            ->select("concat(sekolah.Nama, ', ', sekolah.Alamat) as sekolahNamaAlamat")
            ->from($this->table)
            ->join('t01_csiswa csiswa', 'csiswa.idcsiswa = ' . $this->table . '.idcsiswa', 'left')
            ->join('t00_sekolah sekolah', 'sekolah.idsekolah = ' . $this->table . '.idsekolah', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('csiswa.Nama', $q);
        $this->db->or_like('csiswa.Alamat', $q);
		$this->db->or_like('sekolah.Nama', $q);
        $this->db->or_like('sekolah.Alamat', $q);
		$this->db->limit($limit, $start);
        $this->db
            ->select($this->table . '.*')
            ->select("concat(csiswa.Nama, ', ', csiswa.Alamat) as csiswaNamaAlamat")
            ->select("concat(sekolah.Nama, ', ', sekolah.Alamat) as sekolahNamaAlamat")
            ->from($this->table)
            ->join('t01_csiswa csiswa', 'csiswa.idcsiswa = ' . $this->table . '.idcsiswa', 'left')
            ->join('t00_sekolah sekolah', 'sekolah.idsekolah = ' . $this->table . '.idsekolah', 'left');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        // echo $this->db
        // ->limit(1)
        // ->get_where($this->table, "idcsiswa = '" . $data['idcsiswa'] . "' and idsekolah = '" . $data['idsekolah'] . "'")
        // ->num_rows() === 0;
        // exit;
        if (
            $this->db
            ->limit(1)
            ->get_where($this->table, "idcsiswa = '" . $data['idcsiswa'] . "'")
            ->num_rows() === 0
        ) {
            $this->db->insert($this->table, $data);
        }
        return ($this->db->trans_status()) ? $this->db->insert_id() : false;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T30_csiswa_sekolah_model.php */
/* Location: ./application/models/T30_csiswa_sekolah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-16 03:48:18 */
/* http://harviacode.com */
